name: 'C++ API Documentation'
description: 'Generate and publish Doxygen documentation'
inputs:
  version:
    description: 'Version to publish'
    required: false
  repo-name:
    description: 'Repository name'
    required: true

runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install Python dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install packaging

    - name: Check version
      if: inputs.version != ''
      shell: python
      run: ${{ github.action_path }}/scripts/check_version.py "${{ inputs.version }}"

    - name: Patch Doxyfile
      shell: python
      run: |
        python ${{ github.action_path }}/scripts/patch_doxyfile.py "${{ inputs.version }}"

    - name: Generate documentation
      uses: mattnotmitt/doxygen-action@v1.9.2
      with:
        working-directory: .github/doxygen/
        doxyfile-path: ./Doxyfile

    - name: Prepare documentation
      shell: python
      run: |
        python ${{ github.action_path }}/scripts/prepare_documentation.py \
          --repo-name "${{ inputs.repo-name }}" \
          --version "${{ inputs.version }}"