name: Test C++ Documentation Action
on:
  pull_request:
    paths:
      - 'doxygen/action.yml'
      - '.github/workflows/test-cpp-docs.yml'
      - 'doxygen/scripts/**'
      - 'doxygen/doxygen/**'
  push:
    branches: [ main ]
    paths:
      - 'doxygen/action.yml'
      - '.github/workflows/test-cpp-docs.yml'
      - 'doxygen/scripts/**'
      - 'doxygen/doxygen/**'
  workflow_dispatch:

jobs:
  test-cpp-docs:
    name: Test C++ Doxygen Action
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Git User
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Setup gh-pages branch
        run: |
          git fetch origin gh-pages || git checkout --orphan gh-pages
          git checkout gh-pages || true
          git pull origin gh-pages || true
          git checkout ${{ github.sha }}

      # Test RC version
      - name: Create test environment for RC
        run: |
          mkdir -p .github/doxygen/test/src .github/doxygen/out/html

          # Create CMakeLists.txt with RC version
          cat > CMakeLists.txt << 'EOL'
          cmake_minimum_required(VERSION 3.10)
          project(KeypopDocs
              VERSION 1.0.0
              DESCRIPTION "Keypop Documentation"
              LANGUAGES CXX
          )
          set(RC_VERSION "1")
          EOL

          # Create example header file
          cat > .github/doxygen/test/src/example.h << 'EOL'
          /**
           * @brief Example class for testing C++ documentation
           */
          class Example {
          public:
              /** Do something */
              void doSomething();
          };
          EOL

          # Create Doxyfile
          cat > .github/doxygen/Doxyfile << 'EOL'
          PROJECT_NAME           = "C++ Test Project"
          OUTPUT_DIRECTORY       = out
          GENERATE_HTML         = YES
          HTML_OUTPUT          = html
          INPUT                = test/src
          FILE_PATTERNS        = *.h
          RECURSIVE           = YES
          EOL

      # Test RC version
      - name: Test docs with RC version
        uses: ./doxygen
        with:
          repo-name: keypop-action-docs
          version: "1.0.0-rc1"

      - name: Verify RC version docs
        run: |
          cd keypop-action-docs
          if [ ! -d "1.0.0-rc1" ]; then
            echo "RC version directory was not created"
            exit 1
          fi

      # Test non-RC version
      - name: Create test environment for release
        run: |
          # Update CMakeLists.txt without RC version
          cat > CMakeLists.txt << 'EOL'
          cmake_minimum_required(VERSION 3.10)
          project(KeypopDocs
              VERSION 1.0.0
              DESCRIPTION "Keypop Documentation"
              LANGUAGES CXX
          )
          EOL

      - name: Test docs with release version
        uses: ./doxygen
        with:
          repo-name: keypop-action-docs
          version: "1.0.0"

      - name: Verify release version docs
        run: |
          cd keypop-action-docs
          if [ ! -d "1.0.0" ]; then
            echo "Release version directory was not created"
            exit 1
          fi
          if [ ! -L "latest-stable" ]; then
            echo "latest-stable symlink was not created"
            exit 1
          fi
          if [ ! -f "robots.txt" ]; then
            echo "robots.txt was not created"
            exit 1
          fi