name: Test C++ Documentation Action
on:
  pull_request:
    paths:
      - 'doxygen/action.yml'
      - '.github/workflows/test-cpp-docs.yml'
      - 'doxygen/scripts/**'
      - 'doxygen/doxygen/**'
  push:
    branches: [ main ]
    paths:
      - 'doxygen/action.yml'
      - '.github/workflows/test-cpp-docs.yml'
      - 'doxygen/scripts/**'
      - 'doxygen/doxygen/**'
  workflow_dispatch:

jobs:
  test-cpp-docs:
    name: Test C++ Doxygen Action
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: doxygen

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Create test files
      - name: Create test environment
        run: |
          # Create CMakeLists.txt
          cat > CMakeLists.txt << 'EOL'
          cmake_minimum_required(VERSION 3.10)
          project(KeypopDocs
              VERSION 1.0.0
              DESCRIPTION "Keypop Documentation"
              LANGUAGES CXX
          )
          set(PROJECT_VERSION_MAJOR 1)
          set(PROJECT_VERSION_MINOR 0)
          set(PROJECT_VERSION_PATCH 0)
          EOL

          # Create test directory
          mkdir -p .github/doxygen/test/src

          # Create example C++ file for documentation
          cat > .github/doxygen/test/src/example.h << 'EOL'
          /**
           * @brief Example class for testing C++ documentation
           */
          class Example {
          public:
              /** Do something */
              void doSomething();
          };
          EOL

          # Create test Doxyfile
          cat > .github/doxygen/Doxyfile << 'EOL'
          PROJECT_NAME           = "C++ Test Project"
          OUTPUT_DIRECTORY       = docs
          GENERATE_HTML         = YES
          HTML_OUTPUT          = html
          INPUT                = test/src
          FILE_PATTERNS        = *.h
          RECURSIVE           = YES
          EOL

      # Test with no version
      - name: Test docs without version
        uses: ./doxygen
        with:
          repo-name: ${{ github.event.repository.name }}

      - name: Verify docs without version
        run: |
          if [ ! -f ".github/doxygen/docs/html/index.html" ]; then
            echo "Documentation was not generated"
            exit 1
          fi

      # Test with version
      - name: Test docs with version
        uses: ./doxygen
        with:
          repo-name: ${{ github.event.repository.name }}
          version: "1.0.0"

      - name: Verify docs with version
        run: |
          if [ ! -f ".github/doxygen/docs/html/index.html" ]; then
            echo "Documentation was not generated"
            exit 1
          fi
          if ! grep -q "1.0.0" ".github/doxygen/docs/html/index.html"; then
            echo "Version number not found in documentation"
            exit 1
          fi

      # Test with invalid version
      - name: Test docs with invalid version
        id: invalid-version
        continue-on-error: true
        uses: ./doxygen
        with:
          repo-name: ${{ github.event.repository.name }}
          version: "invalid"

      - name: Verify invalid version fails
        if: steps.invalid-version.outcome == 'success'
        run: |
          echo "Action should have failed with invalid version"
          exit 1